kind: Template
apiVersion: template.openshift.io/v1
metadata:
  name: oauth-server-template

parameters:
  - description: openshift namespace prefix
    name: NAMESPACE_PREFIX
    required: true
  - description: openshift namespace env name
    name: ENV
    required: true
  - description: app name
    name: APP_NAME
    required: true
  - description: image tag for deployments
    name: TAG
    required: true
  - description: ASPNET runtime environment (Development/Staging/Production)
    name: RUNTIME_ENVIRONMENT
    value: Staging
  - description: REDIS Service connection string
    name: REDIS_CONNECTIONSTRING
    required: false
  - description: BCSC identity provider client id
    name: BCSC_CLIENTID
    required: false
  - description: BCSC identity provider client secret
    name: BCSC_CLIENTSECRET
    required: false
  - description: BCSC identity provider metadata address
    name: BCSC_METADATAADDRESS
    required: false
  - description: splunk url
    name: SPLUNK_URL
    required: false
  - description: splunk token
    name: SPLUNK_TOKEN
    required: false
        
objects:
  - kind: ConfigMap
    apiVersion: v1
    metadata:
      name: ${APP_NAME}-oauth-server-config
      namespace: ${NAMESPACE_PREFIX}-${ENV}
      labels:
        app: ${APP_NAME}        
    data:
      APP_NAME: ${APP_NAME}-oauth-server
      ASPNETCORE_ENVIRONMENT: ${RUNTIME_ENVIRONMENT}
      KEY_RING_PATH: "/dpkeys"

  - kind: Secret
    apiVersion: v1
    type: Opaque
    metadata:
      name: ${APP_NAME}-oauth-server-secrets
      namespace: ${NAMESPACE_PREFIX}-${ENV}
      labels:
        app: ${APP_NAME}-oauth-server
    stringData:
      REDIS_CONNECTIONSTRING: ${REDIS_CONNECTIONSTRING}
      ConnectionStrings__DefaultConnection: "Data Source=/dpkeys/IdentityServer.db;"
      identityProviders__bcsc__clientId : "${BCSC_CLIENTID}"
      identityProviders__bcsc__clientSecret : "${BCSC_CLIENTSECRET}"
      identityProviders__bcsc__metadataAddress : "${BCSC_METADATAADDRESS}"
      SPLUNK_URL: ${SPLUNK_URL}
      SPLUNK_TOKEN: ${SPLUNK_TOKEN}

  - kind: Service
    apiVersion: v1
    metadata:
      labels:
        app: ${APP_NAME}-oauth-server
      name: ${APP_NAME}-oauth-server
      namespace: ${NAMESPACE_PREFIX}-${ENV}
      annotations:
        service.alpha.openshift.io/serving-cert-secret-name: ${APP_NAME}-oauth-server-ssl
    spec:
      ports:
        - name: 8080-tcp
          port: 8080
          protocol: TCP
          targetPort: 8080
      selector:
        deploymentconfig: ${APP_NAME}-oauth-server
      type: ClusterIP

  - kind: Route
    apiVersion: route.openshift.io/v1
    metadata:
      labels:
        app: ${APP_NAME}-oauth-server
      annotations:
        haproxy.router.openshift.io/hsts_header: max-age=31536000;includeSubDomains;preload
        haproxy.router.openshift.io/balance: leastconn
      name: ${APP_NAME}-era-oauth-server
      namespace: ${NAMESPACE_PREFIX}-${ENV}
    spec:
      host: ${APP_NAME}-era-auth.apps.silver.devops.gov.bc.ca
      path: /
      port:
        targetPort: 8080-tcp
      tls:
        insecureEdgeTerminationPolicy: Redirect
        termination: edge
      to:
        kind: Service
        name: ${APP_NAME}-oauth-server
        weight: 100

  - kind: NetworkPolicy
    apiVersion: networking.k8s.io/v1
    metadata:
      name: ${APP_NAME}-oauth-server
      labels:
        app: ${APP_NAME}-oauth-server
      namespace: ${NAMESPACE_PREFIX}-${ENV}
    spec:
      podSelector:
        matchLabels:
          app: ${APP_NAME}-oauth-server
      ingress:
        - ports:
            - protocol: TCP
              port: 8080

  - kind: DeploymentConfig
    apiVersion: apps.openshift.io/v1
    metadata:
      labels:
        app: ${APP_NAME}-oauth-server
      name: ${APP_NAME}-oauth-server
      namespace: ${NAMESPACE_PREFIX}-${ENV}
    spec:
      replicas: 2
      revisionHistoryLimit: 2
      selector:
        deploymentconfig: ${APP_NAME}-oauth-server
      strategy:
        type: Rolling
        resources:
          limits:
            cpu: 15m
            memory: 64Mi
          requests:
            cpu: 5m
            memory: 32Mi
        rollingParams:
          intervalSeconds: 1
          maxSurge: 25%
          maxUnavailable: 25%
          timeoutSeconds: 600
          updatePeriodSeconds: 1
      template:
        metadata:
          labels:
            app: ${APP_NAME}-oauth-server
            deploymentconfig: ${APP_NAME}-oauth-server
        spec:
          containers:
            - name: oauth-server
              resources:
                limits:
                  cpu: 50m
                  memory: 256Mi
                requests:
                  cpu: 10m
                  memory: 64Mi
              env:
                - name: "ASPNETCORE_Kestrel__Certificates__Default__Path"
                  value: "/ssl/tls.crt"
                - name: "ASPNETCORE_Kestrel__Certificates__Default__KeyPath"
                  value: "/ssl/tls.key"
              envFrom:
                - configMapRef:
                    name: ${APP_NAME}-oauth-server-config
                - secretRef:
                    name: ${APP_NAME}-oauth-server-secrets
              image: docker-registry.default.svc:5000/${NAMESPACE_PREFIX}-tools/oauth-server:${TAG}
              imagePullPolicy: Always
              volumeMounts:
                - mountPath: /ssl
                  name: ssl
                  readonly: true
                - mountPath: /dpkeys
                  name: dp
              livenessProbe:
                httpGet:
                  path: /hc/live
                  port: 8080
                timeoutSeconds: 10
                periodSeconds: 60
                successThreshold: 1
                failureThreshold: 5
              startupProbe:
                httpGet:
                  path: /.well-known/openid-configuration
                  port: 8080
                initialDelaySeconds: 30
                timeoutSeconds: 10
                periodSeconds: 15
                successThreshold: 1
                failureThreshold: 5
              readinessProbe:
                httpGet:
                  path: /hc/ready
                  port: 8080
                timeoutSeconds: 5
                periodSeconds: 60
                successThreshold: 1
                failureThreshold: 5
          dnsPolicy: ClusterFirst
          restartPolicy: Always
          schedulerName: default-scheduler
          securityContext: {}
          terminationGracePeriodSeconds: 30
          volumes:
            - name: ssl
              secret:
                secretName: ${APP_NAME}-oauth-server-ssl
            - name: dp
              persistentVolumeClaim:
                claimName: ${APP_NAME}-oauth-server-data-protection
      test: false
      triggers:
        - type: ConfigChange
        - type: ImageChange
          imageChangeParams:
            automatic: true
            containerNames:
              - oauth-server
            from:
              kind: ImageStreamTag
              name: oauth-server:${TAG}
              namespace: ${NAMESPACE_PREFIX}-tools

  - kind: HorizontalPodAutoscaler
    apiVersion: autoscaling/v2beta2
    metadata:
      name: ${APP_NAME}-oauth-server-has
      namespace: ${NAMESPACE_PREFIX}-${ENV}
      labels:
        app: ${APP_NAME}-oauth-server
    spec:
      scaleTargetRef:
        kind: DeploymentConfig
        name: ${APP_NAME}-oauth-server
        apiVersion: apps.openshift.io/v1
      minReplicas: 3
      maxReplicas: 6
      metrics:
        - type: Resource
          resource:
            name: cpu
            target:
              type: Utilization
              averageUtilization: 100
        - type: Resource
          resource:
            name: memory
            target:
              type: Utilization
              averageUtilization: 175

  - kind: "PersistentVolumeClaim"
    apiVersion: "v1"
    metadata:
      name: ${APP_NAME}-oauth-server-data-protection
      namespace: ${NAMESPACE_PREFIX}-${ENV}
      labels:
        app: ${APP_NAME}
    spec:
      accessModes:
        - "ReadWriteMany"
      resources:
        requests:
          storage: "512Mi"