version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/ess/src/API"
    schedule:
      interval: "weekly"
  - package-ecosystem: "nuget"
    directory: "/responders/src/API"
    schedule:
      interval: "weekly"
  - package-ecosystem: "nuget"
    directory: "/registrants/src/API"
    schedule:
      interval: "weekly"
  - package-ecosystem: "nuget"
    directory: "/suppliers/src/API"
    schedule:
      interval: "weekly"
  - package-ecosystem: "nuget"
    directory: "/oauth-server/src/API"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
