kind: Template
apiVersion: v1
metadata:
  name: pdf-generator-template

parameters:
  - description: openshift namespace prefix
    name: NAMESPACE_PREFIX
    required: true
  - description: openshift namespace env name
    name: ENV
    required: true
  - description: app name
    name: APP_NAME
    required: true
  - description: image tag for deployments
    name: TAG
    required: true
  - description: ASPNET runtime environment (Development/Staging/Production)
    name: RUNTIME_ENVIRONMENT
    value: Staging

objects:
  - kind: ConfigMap
    apiVersion: v1
    metadata:
      name: ${APP_NAME}-pdf-generator-config
      namespace: ${NAMESPACE_PREFIX}-${ENV}
      labels:
        app: ${APP_NAME}-pdf-generator
        app.kubernetes.io/part-of: ${APP_NAME}
    data:
      ASPNETCORE_ENVIRONMENT: ${RUNTIME_ENVIRONMENT}
      KEY_RING_PATH: "/dpkeys"
      CHROME_CACHE_PATH: "/cache"

  - kind: Service
    apiVersion: v1
    metadata:
      labels:
        app: ${APP_NAME}-pdf-generator
        app.kubernetes.io/part-of: ${APP_NAME}
      name: ${APP_NAME}-pdf-generator
      namespace: ${NAMESPACE_PREFIX}-${ENV}
      annotations:
        service.alpha.openshift.io/serving-cert-secret-name: ${APP_NAME}-pdf-generator-ssl
    spec:
      ports:
        - name: 2020-tcp
          port: 2020
          protocol: TCP
          targetPort: 8080
      selector:
        deploymentconfig: ${APP_NAME}-pdf-generator
      type: ClusterIP

  - kind: NetworkPolicy
    apiVersion: networking.k8s.io/v1
    metadata:
      name: ${APP_NAME}-pdf-generator
      labels:
        app: ${APP_NAME}-pdf-generator
        app.kubernetes.io/part-of: ${APP_NAME}
      namespace: ${NAMESPACE_PREFIX}-${ENV}
    spec:
      podSelector:
        matchLabels:
          app: ${APP_NAME}-pdf-generator
      policyTypes:
        - Ingress
      ingress:
        - from:
            - podSelector:
                matchLabels:
                  app.kubernetes.io/part-of: ${APP_NAME}
                  role: backend
          ports:
            - protocol: TCP
              port: 8080

  - kind: DeploymentConfig
    apiVersion: apps.openshift.io/v1
    metadata:
      labels:
        app: ${APP_NAME}-pdf-generator
        app.kubernetes.io/part-of: ${APP_NAME}
      name: ${APP_NAME}-pdf-generator
      namespace: ${NAMESPACE_PREFIX}-${ENV}
    spec:
      replicas: 2
      selector:
        deploymentconfig: ${APP_NAME}-pdf-generator
      strategy:
        activeDeadlineSeconds: 21600
        resources: {}
        rollingParams:
          intervalSeconds: 1
          maxSurge: 25%
          maxUnavailable: 25%
          timeoutSeconds: 600
          updatePeriodSeconds: 1
        type: Rolling
      template:
        metadata:
          labels:
            app: ${APP_NAME}-pdf-generator
            app.kubernetes.io/part-of: ${APP_NAME}
            deploymentconfig: ${APP_NAME}-pdf-generator
        spec:
          containers:
            - name: pdf-generator
              env:
                - name: "ASPNETCORE_Kestrel__Certificates__Default__Path"
                  value: "/ssl/tls.crt"
                - name: "ASPNETCORE_Kestrel__Certificates__Default__KeyPath"
                  value: "/ssl/tls.key"
              envFrom:
                - configMapRef:
                    name: ${APP_NAME}-pdf-generator-config
              image: docker-registry.default.svc:5000/${NAMESPACE_PREFIX}-tools/pdf-generator:${TAG}
              imagePullPolicy: Always
              volumeMounts:
                - mountPath: /ssl
                  name: ssl
                  readonly: true
                - mountPath: /dpkeys
                  name: dp-keys
                - mountPath: /cache
                  name: cache
              livenessProbe:
                httpGet:
                  scheme: HTTPS
                  path: /hc/live
                  port: 8080
              startupProbe:
                httpGet:
                  scheme: HTTPS
                  path: /hc/startup
                  port: 8080
              readinessProbe:
                httpGet:
                  scheme: HTTPS
                  path: /hc/ready
                  port: 8080
          dnsPolicy: ClusterFirst
          restartPolicy: Always
          schedulerName: default-scheduler
          securityContext: {}
          terminationGracePeriodSeconds: 30
          volumes:
            - name: ssl
              secret:
                secretName: ${APP_NAME}-pdf-generator-ssl
            - name: dp-keys
              persistentVolumeClaim:
                claimName: ${APP_NAME}-pdf-generator-key-ring
            - name: cache
              persistentVolumeClaim:
                claimName: ${APP_NAME}-pfd-generator-cache
      test: false
      triggers:
        - type: ConfigChange
        - type: ImageChange
          imageChangeParams:
            automatic: true
            containerNames:
              - pdf-generator
            from:
              kind: ImageStreamTag
              name: pdf-generator:${TAG}
              namespace: ${NAMESPACE_PREFIX}-tools

  - kind: "PersistentVolumeClaim"
    apiVersion: "v1"
    metadata:
      name: ${APP_NAME}-pdf-generator-key-ring
      namespace: ${NAMESPACE_PREFIX}-${ENV}
      labels:
        app: ${APP_NAME}-pdf-generator
        app.kubernetes.io/part-of: ${APP_NAME}
    spec:
      accessModes:
        - "ReadWriteMany"
      resources:
        requests:
          storage: "100Mi"

  - kind: "PersistentVolumeClaim"
    apiVersion: "v1"
    metadata:
      name: ${APP_NAME}-pfd-generator-cache
      namespace: ${NAMESPACE_PREFIX}-${ENV}
      labels:
        app: ${APP_NAME}-pdf-generator
        app.kubernetes.io/part-of: ${APP_NAME}
    spec:
      accessModes:
        - "ReadWriteMany"
      resources:
        requests:
          storage: "1024Mi"
