version: "3"

services:
  suppliers-portal-api:
    build:
      context: ./suppliers/src/API
    image: embcess-suppliers-api:dev
    ports:
      - 7020:8080
    env_file:
      - .env
    depends_on:
      - ess-backend

  suppliers-portal-ui:
    build:
      context: ./suppliers/src/UI
    image: embcess-suppliers-ui:dev
    ports:
      - 7200:2015
    environment:
      - "API_URL=suppliers-portal-api:8080"
    depends_on:
      - suppliers-portal-api
      
  registrants-portal-api:
    build:
      context: ./evacuees/src/API
    image: embcess-registrants-api:dev
    ports:
      - 5020:8080
    env_file:
      - .env
    depends_on:
      - ess-backend

  registrants-portal-ui:
    build:
      context: ./evacuees/src/UI
    image: embcess-registrants-ui:dev
    ports:
      - 5200:2015
    environment:
      - "API_URL=registrants-portal-api:8080"
      - "LOG_LEVEL=DEBUG"
    depends_on:
      - registrants-portal-api

  responders-portal-api:
    build:
      context: ./responders/src/API
    image: embcess-responders-api:dev
    ports:
      - 6020:8080
    environment:
      - "BE__URL=ess-backend:8080"
    env_file:
      - .env
    depends_on:
      - ess-backend

  responders-portal-ui:
    build:
      context: ./responders/src/UI
    image: embcess-responders-ui:dev
    ports:
      - 6200:2015
    environment:
      - "API_URL=responders-portal-api:8080"
    depends_on:
      - responders-portal-api
  
  ess-backend:
    build:
      context: ./ess/src/API
    image: embcess-backend-api:dev
    ports:
      - 2020:8080
    env_file:
      - .env
    environment:
    - "ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx"
    volumes:
      - $USERPROFILE\.aspnet\https:/https/