version: "3"

services:
  suppliers-portal-api:
    build:
      context: ./suppliers/src/API
    image: embcess-suppliers-api:dev
    ports:
      - 8080:8080
    env_file:
      - .env

  suppliers-portal-ui:
    build:
      context: ./suppliers/src/UI
    image: embcess-suppliers-ui:dev
    ports:
      - 2015:2015
    environment:
      - "API_URL=suppliers-portal-api:8080"
    depends_on:
      - suppliers-portal-api
