version: "3"

services:
  suppliers-portal-api:
    build:
      context: ./suppliers/src/API
    image: embcess-suppliers-api:dev
    ports:
      - 1010:8080
    env_file:
      - .env

  suppliers-portal-ui:
    build:
      context: ./suppliers/src/UI
    image: embcess-suppliers-ui:dev
    ports:
      - 4200:2015
    environment:
      - "API_URL=suppliers-portal-api:8080"
    depends_on:
      - suppliers-portal-api
      
  registrants-portal-api:
    build:
      context: ./evacuees/src/API
    image: embcess-registrants-api:dev
    ports:
      - 2010:8080
    env_file:
      - .env

  registrants-portal-ui:
    build:
      context: ./evacuees/src/UI
    image: embcess-registrants-ui:dev
    ports:
      - 5200:2015
    environment:
      - "API_URL=registrants-portal-api:8080"
    depends_on:
      - registrants-portal-api

  responders-portal-api:
    build:
      context: ./responders/src/API
    image: embcess-responders-api:dev
    ports:
      - 3010:8080
    env_file:
      - .env

  responders-portal-ui:
    build:
      context: ./responders/src/UI
    image: embcess-responders-ui:dev
    ports:
      - 6200:2015
    environment:
      - "API_URL=responders-portal-api:8080"
    depends_on:
      - responders-portal-api
