version: "3"

services:
  suppliers-portal-api:
    build:
      context: ./suppliers/src/API
    image: embcess-suppliers-api:dev
    ports:
      - 1010:8080
    env_file:
      - .env

  suppliers-portal-ui:
    build:
      context: ./suppliers/src/UI
    image: embcess-suppliers-ui:dev
    ports:
      - 1015:2015
    environment:
      - "API_URL=suppliers-portal-api:8080"
    depends_on:
      - suppliers-portal-api
      
  evacuees-portal-api:
    build:
      context: ./evacuees/src/API
    image: embcess-evacuees-api:dev
    ports:
      - 2010:8080
    env_file:
      - .env

  evacuees-portal-ui:
    build:
      context: ./evacuees/src/UI
    image: embcess-evacuees-ui:dev
    ports:
      - 2015:2015
    environment:
      - "API_URL=evacuees-portal-api:8080"
    depends_on:
      - evacuees-portal-api
