kind: Template
apiVersion: template.openshift.io/v1
metadata:
  name: mygovbc-captcha-service build config template

parameters:
  - description: openshift namespace prefix
    name: NAMESPACE_PREFIX
    required: true

objects:
  - kind: ImageStream
    apiVersion: image.openshift.io/v1
    metadata:
      name: mygovbc-captcha-service
      namespace: ${NAMESPACE_PREFIX}-tools

  - kind: BuildConfig
    apiVersion: build.openshift.io/v1
    metadata:
      name: mygovbc-captcha-service-build
      namespace: ${NAMESPACE_PREFIX}-tools
      labels:
        app: mygovbc-captcha-service
    spec:
      output:
        to:
          kind: ImageStreamTag
          name: "mygovbc-captcha-service:latest"
      successfulBuildsHistoryLimit: 5
      failedBuildsHistoryLimit: 5
      strategy:
        type: Source
        sourceStrategy:
          from:
            kind: ImageStreamTag
            namespace: openshift
            name: 'nodejs:10'
      postCommit: {}
      source:
        type: Git
        git:
          uri: "https://github.com/bcgov/MyGovBC-CAPTCHA-Service.git"
          ref: master
      triggers:
        - type: ConfigChange
        - type: GitHub
          github:
            secretReference:
              name: webhook
      runPolicy: Serial
