name: ci-suppliers-portal-ui

on:
  pull_request:
    types: [synchronize]
    paths:
      - "suppliers/src/UI"
      - ".github/workflows/ci-suppliers-portal-ui.yml"

env:
  IMAGE_NAME: suppliers-portal-ui

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build image
        working-directory: ./suppliers/src/UI
        run: docker build . --file Dockerfile --tag $IMAGE_NAME
