name: ci-suppliers-portal-ui

on:
  pull_request:
    types: [opened, reopened, edited, synchronize]
    paths:
      - "suppliers/src/UI/**"
      - ".github/workflows/ci-suppliers-portal-ui.yml"

env:
  IMAGE_NAME: suppliers-portal-ui

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Log into registry
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set image repository
        id: set_image_repository
        run: |
          # Set image repository and change all uppercase to lowercase
          DOCKER_REPOSITORY=$(echo ${{ secrets.DOCKER_REGISTRY }}/${{ env.IMAGE_NAME }} | tr '[A-Z]' '[a-z]')
          echo "::set-output name=docker-repository::$DOCKER_REPOSITORY"
          
      - name: Pull image
        env:
          DOCKER_REPOSITORY: ${{ steps.set_image_repository.outputs.docker-repository }}
        run: docker pull $DOCKER_REPOSITORY:latest || true

      - name: Build image
        working-directory: ./suppliers/src/UI
        run: docker build . --file Dockerfile --tag $IMAGE_NAME
