name: ESS Contracts nuget workflow

on:
  release:
    types: [created]
    paths:
        - "ess/src/API/EMBC.ESS.Shared.Contracts/**"
        - ".github/workflows/release-ess-contracts-nuget.yml"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-dotnet@v1
      with:
          dotnet-version: '3.1.x' # SDK Version to use.
          source-url: https://nuget.pkg.github.com/bcgov/embc-ess-mod/index.json
    - env:
        NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
    - name: build
      run: dotnet build ess/src/API/EMBC.ESS.Shared.Contracts/
    - name: pack
      run: dotnet pack --configuration Release ess/src/API/EMBC.ESS.Shared.Contracts/
    - name: push
      run: dotnet nuget push ess/src/API/EMBC.ESS.Shared.Contracts//bin/Release/*.nupkg
